name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: pip install -r requirements/linting.txt -r requirements/pyproject.txt

    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files

  test:
    name: test py${{ matrix.python }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python: ['3.7', '3.8', '3.9', '3.10', '3.11-dev']

    env:
      PYTHON: ${{ matrix.python }}
      OS: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - run: pip install -r requirements/testing.txt -r requirements/pyproject.txt

    - run: make test

    - run: coverage xml

    - uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        env_vars: PYTHON,OS

  deploy:
    name: Deploy
    needs: [lint, test]
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install
        run: pip install -U twine build packaging

      - name: check version
        id: check-version
        run: python <(curl -Ls https://gist.githubusercontent.com/samuelcolvin/4e1ad439c5489e8d6478cdee3eb952ef/raw/check_version.py)
        env:
          VERSION_PATH: 'pydantic_settings/version.py'

      - name: build
        run: python -m build

      - run: twine check dist/*

      - name: upload to pypi
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
